const WORD_DATA = {
  textbook: {
    grade7a: [
      {
        id: "7a_village",
        name: "🏘️ 新手村",
        title: "踏上冒险的第一步",
        words: [
          { en: "hello", zh: "你好", phonetic: "/həˈləʊ/" },
          { en: "friend", zh: "朋友", phonetic: "/frend/" },
          { en: "name", zh: "名字", phonetic: "/neɪm/" },
          { en: "age", zh: "年龄", phonetic: "/eɪdʒ/" },
          { en: "family", zh: "家庭", phonetic: "/ˈfæməli/" },
          { en: "parents", zh: "父母", phonetic: "/ˈpeərənts/" },
          { en: "country", zh: "国家", phonetic: "/ˈkʌntri/" },
          { en: "China", zh: "中国", phonetic: "/ˈtʃaɪnə/" },
          { en: "world", zh: "世界", phonetic: "/wɜːld/" },
          { en: "dream", zh: "梦想", phonetic: "/driːm/" },
          { en: "hobby", zh: "爱好", phonetic: "/ˈhɒbi/" },
          { en: "everyone", zh: "每个人", phonetic: "/ˈevriwʌn/" },
          { en: "German", zh: "德国的；德国人", phonetic: "/ˈdʒɜːmən/" },
          { en: "Japan", zh: "日本", phonetic: "/dʒəˈpæn/" },
          { en: "yourself", zh: "你自己", phonetic: "/jɔːˈself/" },
          { en: "close", zh: "近的；亲密的", phonetic: "/kləʊs/" },
          { en: "friendly", zh: "友好的", phonetic: "/ˈfrendli/" },
          { en: "excellent", zh: "优秀的", phonetic: "/ˈeksələnt/" },
          { en: "sound", zh: "声音", phonetic: "/saʊnd/" },
          { en: "complete", zh: "完成", phonetic: "/kəmˈpliːt/" },
          { en: "elder", zh: "年长的", phonetic: "/ˈeldər/" },
          { en: "engineer", zh: "工程师", phonetic: "/ˌendʒɪˈnɪr/" },
          { en: "blog", zh: "博客", phonetic: "/blɒɡ/" },
          { en: "information", zh: "信息", phonetic: "/ˌɪnfəˈmeɪʃn/" },
          { en: "flat", zh: "公寓", phonetic: "/flæt/" },
          { en: "mountain", zh: "山", phonetic: "/ˈmaʊntən/" },
          { en: "welcome", zh: "欢迎", phonetic: "/ˈwelkəm/" },
          { en: "together", zh: "一起", phonetic: "/təˈɡeðər/" },
          { en: "different", zh: "不同的", phonetic: "/ˈdɪfrənt/" },
          { en: "live", zh: "居住；生活", phonetic: "/lɪv/" },
        ]
      },
      {
        id: "7a_meadow",
        name: "🌅 晨光草原",
        title: "每天的冒险日常",
        words: [
          { en: "daily", zh: "每日的", phonetic: "/ˈdeɪli/" },
          { en: "morning", zh: "早晨", phonetic: "/ˈmɔːnɪŋ/" },
          { en: "evening", zh: "傍晚", phonetic: "/ˈiːvnɪŋ/" },
          { en: "usually", zh: "通常", phonetic: "/ˈjuːʒuəli/" },
          { en: "never", zh: "从不", phonetic: "/ˈnevər/" },
          { en: "always", zh: "总是", phonetic: "/ˈɔːlweɪz/" },
          { en: "sometimes", zh: "有时", phonetic: "/ˈsʌmtaɪmz/" },
          { en: "often", zh: "经常", phonetic: "/ˈɒfn/" },
          { en: "breakfast", zh: "早餐", phonetic: "/ˈbrekfəst/" },
          { en: "lunch", zh: "午餐", phonetic: "/lʌntʃ/" },
          { en: "dinner", zh: "晚餐", phonetic: "/ˈdɪnər/" },
          { en: "begin", zh: "开始", phonetic: "/bɪˈɡɪn/" },
          { en: "end", zh: "结束", phonetic: "/end/" },
          { en: "break", zh: "休息；打破", phonetic: "/breɪk/" },
          { en: "arrive", zh: "到达", phonetic: "/əˈraɪv/" },
          { en: "wash", zh: "洗", phonetic: "/wɒʃ/" },
          { en: "brush", zh: "刷", phonetic: "/brʌʃ/" },
          { en: "prepare", zh: "准备", phonetic: "/prɪˈpeər/" },
          { en: "exercise", zh: "锻炼", phonetic: "/ˈeksəsaɪz/" },
          { en: "practice", zh: "练习", phonetic: "/ˈpræktɪs/" },
          { en: "collect", zh: "收集", phonetic: "/kəˈlekt/" },
          { en: "enjoy", zh: "享受；喜欢", phonetic: "/ɪnˈdʒɔɪ/" },
          { en: "ride", zh: "骑；乘", phonetic: "/raɪd/" },
          { en: "bell", zh: "铃；钟", phonetic: "/bel/" },
          { en: "between", zh: "在……之间", phonetic: "/bɪˈtwiːn/" },
          { en: "table", zh: "桌子", phonetic: "/ˈteɪbl/" },
          { en: "market", zh: "市场", phonetic: "/ˈmɑːkɪt/" },
          { en: "guitar", zh: "吉他", phonetic: "/ɡɪˈtɑːr/" },
          { en: "grade", zh: "年级；等级", phonetic: "/ɡreɪd/" },
          { en: "article", zh: "文章", phonetic: "/ˈɑːtɪkl/" },
        ]
      },
      {
        id: "7a_forest",
        name: "🌲 魔法森林",
        title: "探索自然的力量",
        words: [
          { en: "nature", zh: "自然", phonetic: "/ˈneɪtʃər/" },
          { en: "forest", zh: "森林", phonetic: "/ˈfɒrɪst/" },
          { en: "earth", zh: "地球；泥土", phonetic: "/ɜːθ/" },
          { en: "field", zh: "田野；领域", phonetic: "/fiːld/" },
          { en: "large", zh: "大的", phonetic: "/lɑːdʒ/" },
          { en: "huge", zh: "巨大的", phonetic: "/hjuːdʒ/" },
          { en: "tiny", zh: "微小的", phonetic: "/ˈtaɪni/" },
          { en: "energy", zh: "能量", phonetic: "/ˈenədʒi/" },
          { en: "ground", zh: "地面", phonetic: "/ɡraʊnd/" },
          { en: "protect", zh: "保护", phonetic: "/prəˈtekt/" },
          { en: "provide", zh: "提供", phonetic: "/prəˈvaɪd/" },
          { en: "pollution", zh: "污染", phonetic: "/pəˈluːʃn/" },
          { en: "kill", zh: "杀死", phonetic: "/kɪl/" },
          { en: "burn", zh: "燃烧", phonetic: "/bɜːn/" },
          { en: "fact", zh: "事实", phonetic: "/fækt/" },
          { en: "own", zh: "自己的", phonetic: "/əʊn/" },
          { en: "catch", zh: "抓住", phonetic: "/kætʃ/" },
          { en: "few", zh: "很少的", phonetic: "/fjuː/" },
          { en: "problem", zh: "问题", phonetic: "/ˈprɒbləm/" },
          { en: "natural", zh: "自然的", phonetic: "/ˈnætʃrəl/" },
          { en: "wild", zh: "野生的", phonetic: "/waɪld/" },
          { en: "free", zh: "自由的", phonetic: "/friː/" },
          { en: "save", zh: "拯救", phonetic: "/seɪv/" },
          { en: "danger", zh: "危险", phonetic: "/ˈdeɪndʒər/" },
          { en: "dangerous", zh: "危险的", phonetic: "/ˈdeɪndʒərəs/" },
          { en: "safe", zh: "安全的", phonetic: "/seɪf/" },
          { en: "important", zh: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
          { en: "grow", zh: "生长", phonetic: "/ɡrəʊ/" },
          { en: "plant", zh: "植物；种植", phonetic: "/plɑːnt/" },
          { en: "wing", zh: "翅膀", phonetic: "/wɪŋ/" },
        ]
      },
      {
        id: "7a_ruins",
        name: "🏛️ 远古遗迹",
        title: "穿越时空的旅行",
        words: [
          { en: "travel", zh: "旅行", phonetic: "/ˈtrævl/" },
          { en: "place", zh: "地方", phonetic: "/pleɪs/" },
          { en: "visit", zh: "参观；拜访", phonetic: "/ˈvɪzɪt/" },
          { en: "guide", zh: "指南；导游", phonetic: "/ɡaɪd/" },
          { en: "building", zh: "建筑物", phonetic: "/ˈbɪldɪŋ/" },
          { en: "modern", zh: "现代的", phonetic: "/ˈmɒdn/" },
          { en: "traditional", zh: "传统的", phonetic: "/trəˈdɪʃənl/" },
          { en: "sightseeing", zh: "观光", phonetic: "/ˈsaɪtsiːɪŋ/" },
          { en: "centre", zh: "中心", phonetic: "/ˈsentər/" },
          { en: "direction", zh: "方向", phonetic: "/dɪˈrekʃn/" },
          { en: "bridge", zh: "桥", phonetic: "/brɪdʒ/" },
          { en: "across", zh: "穿过", phonetic: "/əˈkrɒs/" },
          { en: "along", zh: "沿着", phonetic: "/əˈlɒŋ/" },
          { en: "railway", zh: "铁路", phonetic: "/ˈreɪlweɪ/" },
          { en: "island", zh: "岛屿", phonetic: "/ˈaɪlənd/" },
          { en: "area", zh: "地区", phonetic: "/ˈeəriə/" },
          { en: "square", zh: "广场；正方形", phonetic: "/skweər/" },
          { en: "kilometre", zh: "公里", phonetic: "/kɪˈlɒmɪtər/" },
          { en: "ticket", zh: "票", phonetic: "/ˈtɪkɪt/" },
          { en: "airport", zh: "机场", phonetic: "/ˈeəpɔːt/" },
          { en: "passport", zh: "护照", phonetic: "/ˈpɑːspɔːt/" },
          { en: "foreign", zh: "外国的", phonetic: "/ˈfɒrən/" },
          { en: "local", zh: "当地的", phonetic: "/ˈləʊkl/" },
          { en: "famous", zh: "著名的", phonetic: "/ˈfeɪməs/" },
          { en: "museum", zh: "博物馆", phonetic: "/mjuˈziːəm/" },
          { en: "garden", zh: "花园", phonetic: "/ˈɡɑːdn/" },
          { en: "theatre", zh: "剧院", phonetic: "/ˈθɪətər/" },
          { en: "restaurant", zh: "餐厅", phonetic: "/ˈrestrɒnt/" },
          { en: "hotel", zh: "酒店", phonetic: "/həʊˈtel/" },
          { en: "spend", zh: "花费", phonetic: "/spend/" },
        ]
      },
      {
        id: "7a_academy",
        name: "🏫 智慧学院",
        title: "知识就是力量",
        words: [
          { en: "junior", zh: "初级的", phonetic: "/ˈdʒuːniər/" },
          { en: "subject", zh: "学科；主题", phonetic: "/ˈsʌbdʒɪkt/" },
          { en: "geography", zh: "地理", phonetic: "/dʒiˈɒɡrəfi/" },
          { en: "history", zh: "历史", phonetic: "/ˈhɪstri/" },
          { en: "science", zh: "科学", phonetic: "/ˈsaɪəns/" },
          { en: "maths", zh: "数学", phonetic: "/mæθs/" },
          { en: "language", zh: "语言", phonetic: "/ˈlæŋɡwɪdʒ/" },
          { en: "grammar", zh: "语法", phonetic: "/ˈɡræmər/" },
          { en: "knowledge", zh: "知识", phonetic: "/ˈnɒlɪdʒ/" },
          { en: "understand", zh: "理解", phonetic: "/ˌʌndəˈstænd/" },
          { en: "remember", zh: "记住", phonetic: "/rɪˈmembər/" },
          { en: "forget", zh: "忘记", phonetic: "/fəˈɡet/" },
          { en: "mistake", zh: "错误", phonetic: "/mɪˈsteɪk/" },
          { en: "correct", zh: "正确的", phonetic: "/kəˈrekt/" },
          { en: "term", zh: "学期", phonetic: "/tɜːm/" },
          { en: "classroom", zh: "教室", phonetic: "/ˈklɑːsruːm/" },
          { en: "library", zh: "图书馆", phonetic: "/ˈlaɪbrəri/" },
          { en: "playground", zh: "操场", phonetic: "/ˈpleɪɡraʊnd/" },
          { en: "lab", zh: "实验室", phonetic: "/læb/" },
          { en: "dictionary", zh: "字典", phonetic: "/ˈdɪkʃənri/" },
          { en: "notebook", zh: "笔记本", phonetic: "/ˈnəʊtbʊk/" },
          { en: "textbook", zh: "课本", phonetic: "/ˈtekstbʊk/" },
          { en: "homework", zh: "家庭作业", phonetic: "/ˈhəʊmwɜːk/" },
          { en: "exam", zh: "考试", phonetic: "/ɪɡˈzæm/" },
          { en: "answer", zh: "回答；答案", phonetic: "/ˈɑːnsər/" },
          { en: "question", zh: "问题", phonetic: "/ˈkwestʃən/" },
          { en: "office", zh: "办公室", phonetic: "/ˈɒfɪs/" },
          { en: "chalk", zh: "粉笔", phonetic: "/tʃɔːk/" },
          { en: "blackboard", zh: "黑板", phonetic: "/ˈblækbɔːd/" },
          { en: "would", zh: "愿意", phonetic: "/wʊd/" },
        ]
      },
      {
        id: "7a_kitchen",
        name: "🍳 美食工坊",
        title: "舌尖上的冒险",
        words: [
          { en: "health", zh: "健康", phonetic: "/helθ/" },
          { en: "healthy", zh: "健康的", phonetic: "/ˈhelθi/" },
          { en: "unhealthy", zh: "不健康的", phonetic: "/ʌnˈhelθi/" },
          { en: "vegetable", zh: "蔬菜", phonetic: "/ˈvedʒtəbl/" },
          { en: "fruit", zh: "水果", phonetic: "/fruːt/" },
          { en: "meat", zh: "肉", phonetic: "/miːt/" },
          { en: "chicken", zh: "鸡肉", phonetic: "/ˈtʃɪkɪn/" },
          { en: "beef", zh: "牛肉", phonetic: "/biːf/" },
          { en: "pork", zh: "猪肉", phonetic: "/pɔːk/" },
          { en: "fish", zh: "鱼", phonetic: "/fɪʃ/" },
          { en: "rice", zh: "米饭", phonetic: "/raɪs/" },
          { en: "noodle", zh: "面条", phonetic: "/ˈnuːdl/" },
          { en: "bread", zh: "面包", phonetic: "/bred/" },
          { en: "egg", zh: "鸡蛋", phonetic: "/eɡ/" },
          { en: "milk", zh: "牛奶", phonetic: "/mɪlk/" },
          { en: "water", zh: "水", phonetic: "/ˈwɔːtər/" },
          { en: "juice", zh: "果汁", phonetic: "/dʒuːs/" },
          { en: "sugar", zh: "糖", phonetic: "/ˈʃʊɡər/" },
          { en: "salt", zh: "盐", phonetic: "/sɒlt/" },
          { en: "soup", zh: "汤", phonetic: "/suːp/" },
          { en: "delicious", zh: "美味的", phonetic: "/dɪˈlɪʃəs/" },
          { en: "hungry", zh: "饥饿的", phonetic: "/ˈhʌŋɡri/" },
          { en: "thirsty", zh: "口渴的", phonetic: "/ˈθɜːsti/" },
          { en: "meal", zh: "一餐", phonetic: "/miːl/" },
          { en: "cook", zh: "烹饪；厨师", phonetic: "/kʊk/" },
          { en: "kitchen", zh: "厨房", phonetic: "/ˈkɪtʃɪn/" },
          { en: "fridge", zh: "冰箱", phonetic: "/frɪdʒ/" },
          { en: "taste", zh: "品尝；味道", phonetic: "/teɪst/" },
          { en: "keep", zh: "保持", phonetic: "/kiːp/" },
          { en: "fresh", zh: "新鲜的", phonetic: "/freʃ/" },
        ]
      },
      {
        id: "7a_arena",
        name: "🎮 欢乐竞技场",
        title: "释放你的能量",
        words: [
          { en: "weekend", zh: "周末", phonetic: "/ˌwiːkˈend/" },
          { en: "plan", zh: "计划", phonetic: "/plæn/" },
          { en: "picnic", zh: "野餐", phonetic: "/ˈpɪknɪk/" },
          { en: "forward", zh: "向前", phonetic: "/ˈfɔːwəd/" },
          { en: "cinema", zh: "电影院", phonetic: "/ˈsɪnəmə/" },
          { en: "concert", zh: "音乐会", phonetic: "/ˈkɒnsət/" },
          { en: "match", zh: "比赛", phonetic: "/mætʃ/" },
          { en: "team", zh: "队伍", phonetic: "/tiːm/" },
          { en: "score", zh: "得分", phonetic: "/skɔːr/" },
          { en: "player", zh: "运动员", phonetic: "/ˈpleɪər/" },
          { en: "basketball", zh: "篮球", phonetic: "/ˈbɑːskɪtbɔːl/" },
          { en: "football", zh: "足球", phonetic: "/ˈfʊtbɔːl/" },
          { en: "volleyball", zh: "排球", phonetic: "/ˈvɒlibɔːl/" },
          { en: "tennis", zh: "网球", phonetic: "/ˈtenɪs/" },
          { en: "swimming", zh: "游泳", phonetic: "/ˈswɪmɪŋ/" },
          { en: "skating", zh: "滑冰", phonetic: "/ˈskeɪtɪŋ/" },
          { en: "climbing", zh: "攀登", phonetic: "/ˈklaɪmɪŋ/" },
          { en: "cycling", zh: "骑自行车", phonetic: "/ˈsaɪklɪŋ/" },
          { en: "hiking", zh: "远足", phonetic: "/ˈhaɪkɪŋ/" },
          { en: "camera", zh: "相机", phonetic: "/ˈkæmrə/" },
          { en: "photo", zh: "照片", phonetic: "/ˈfəʊtəʊ/" },
          { en: "video", zh: "视频", phonetic: "/ˈvɪdiəʊ/" },
          { en: "music", zh: "音乐", phonetic: "/ˈmjuːzɪk/" },
          { en: "dance", zh: "跳舞", phonetic: "/dɑːns/" },
          { en: "sing", zh: "唱歌", phonetic: "/sɪŋ/" },
          { en: "draw", zh: "画画", phonetic: "/drɔː/" },
          { en: "paint", zh: "绘画", phonetic: "/peɪnt/" },
          { en: "chess", zh: "国际象棋", phonetic: "/tʃes/" },
          { en: "card", zh: "卡片", phonetic: "/kɑːd/" },
          { en: "shall", zh: "将要", phonetic: "/ʃæl/" },
        ]
      },
      {
        id: "7a_festival",
        name: "🎪 节日广场",
        title: "欢乐的庆典时刻",
        words: [
          { en: "festival", zh: "节日", phonetic: "/ˈfestɪvl/" },
          { en: "celebrate", zh: "庆祝", phonetic: "/ˈselɪbreɪt/" },
          { en: "dragon", zh: "龙", phonetic: "/ˈdræɡən/" },
          { en: "lantern", zh: "灯笼", phonetic: "/ˈlæntən/" },
          { en: "sweet", zh: "甜的", phonetic: "/swiːt/" },
          { en: "luck", zh: "运气", phonetic: "/lʌk/" },
          { en: "lucky", zh: "幸运的", phonetic: "/ˈlʌki/" },
          { en: "Christmas", zh: "圣诞节", phonetic: "/ˈkrɪsməs/" },
          { en: "decorate", zh: "装饰", phonetic: "/ˈdekəreɪt/" },
          { en: "tree", zh: "树", phonetic: "/triː/" },
          { en: "present", zh: "礼物", phonetic: "/ˈpreznt/" },
          { en: "special", zh: "特别的", phonetic: "/ˈspeʃl/" },
          { en: "wonderful", zh: "精彩的", phonetic: "/ˈwʌndəfl/" },
          { en: "firework", zh: "烟花", phonetic: "/ˈfaɪəwɜːk/" },
          { en: "moon", zh: "月亮", phonetic: "/muːn/" },
          { en: "cake", zh: "蛋糕", phonetic: "/keɪk/" },
          { en: "race", zh: "比赛", phonetic: "/reɪs/" },
          { en: "meaning", zh: "意义", phonetic: "/ˈmiːnɪŋ/" },
          { en: "during", zh: "在……期间", phonetic: "/ˈdjʊərɪŋ/" },
          { en: "exciting", zh: "令人兴奋的", phonetic: "/ɪkˈsaɪtɪŋ/" },
          { en: "bright", zh: "明亮的", phonetic: "/braɪt/" },
          { en: "colourful", zh: "多彩的", phonetic: "/ˈkʌləfl/" },
          { en: "quiet", zh: "安静的", phonetic: "/ˈkwaɪət/" },
          { en: "noisy", zh: "吵闹的", phonetic: "/ˈnɔɪzi/" },
          { en: "everywhere", zh: "到处", phonetic: "/ˈevriweər/" },
          { en: "join", zh: "加入", phonetic: "/dʒɔɪn/" },
          { en: "real", zh: "真实的", phonetic: "/rɪəl/" },
          { en: "whole", zh: "整个的", phonetic: "/həʊl/" },
          { en: "card", zh: "贺卡", phonetic: "/kɑːd/" },
          { en: "party", zh: "聚会", phonetic: "/ˈpɑːti/" },
        ]
      },
    ],
    grade7b: [
      {
        id: "7b_town",
        name: "🌃 星光小镇",
        title: "遇见形形色色的人",
        words: [
          { en: "person", zh: "人", phonetic: "/ˈpɜːsn/" },
          { en: "careful", zh: "仔细的", phonetic: "/ˈkeəfl/" },
          { en: "cheerful", zh: "快乐的", phonetic: "/ˈtʃɪəfl/" },
          { en: "patient", zh: "耐心的", phonetic: "/ˈpeɪʃnt/" },
          { en: "smart", zh: "聪明的", phonetic: "/smɑːt/" },
          { en: "clever", zh: "聪明的", phonetic: "/ˈklevər/" },
          { en: "honest", zh: "诚实的", phonetic: "/ˈɒnɪst/" },
          { en: "brave", zh: "勇敢的", phonetic: "/breɪv/" },
          { en: "shy", zh: "害羞的", phonetic: "/ʃaɪ/" },
          { en: "strict", zh: "严格的", phonetic: "/strɪkt/" },
          { en: "encourage", zh: "鼓励", phonetic: "/ɪnˈkʌrɪdʒ/" },
          { en: "support", zh: "支持", phonetic: "/səˈpɔːt/" },
          { en: "successful", zh: "成功的", phonetic: "/səkˈsesfl/" },
          { en: "member", zh: "成员", phonetic: "/ˈmembər/" },
          { en: "joke", zh: "玩笑", phonetic: "/dʒəʊk/" },
          { en: "laugh", zh: "笑", phonetic: "/lɑːf/" },
          { en: "remain", zh: "保持；剩余", phonetic: "/rɪˈmeɪn/" },
          { en: "address", zh: "地址", phonetic: "/əˈdres/" },
          { en: "appear", zh: "出现", phonetic: "/əˈpɪər/" },
          { en: "disappear", zh: "消失", phonetic: "/ˌdɪsəˈpɪər/" },
          { en: "crowd", zh: "人群", phonetic: "/kraʊd/" },
          { en: "alone", zh: "独自的", phonetic: "/əˈləʊn/" },
          { en: "nobody", zh: "没有人", phonetic: "/ˈnəʊbɒdi/" },
          { en: "somebody", zh: "某人", phonetic: "/ˈsʌmbɒdi/" },
          { en: "anybody", zh: "任何人", phonetic: "/ˈenibɒdi/" },
          { en: "strange", zh: "奇怪的", phonetic: "/streɪndʒ/" },
          { en: "ordinary", zh: "普通的", phonetic: "/ˈɔːdnri/" },
          { en: "common", zh: "常见的", phonetic: "/ˈkɒmən/" },
          { en: "popular", zh: "受欢迎的", phonetic: "/ˈpɒpjələr/" },
          { en: "probably", zh: "很可能", phonetic: "/ˈprɒbəbli/" },
        ]
      },
      {
        id: "7b_spring",
        name: "💊 生命之泉",
        title: "守护你的健康",
        words: [
          { en: "head", zh: "头", phonetic: "/hed/" },
          { en: "face", zh: "脸", phonetic: "/feɪs/" },
          { en: "eye", zh: "眼睛", phonetic: "/aɪ/" },
          { en: "nose", zh: "鼻子", phonetic: "/nəʊz/" },
          { en: "mouth", zh: "嘴巴", phonetic: "/maʊθ/" },
          { en: "ear", zh: "耳朵", phonetic: "/ɪər/" },
          { en: "arm", zh: "手臂", phonetic: "/ɑːm/" },
          { en: "hand", zh: "手", phonetic: "/hænd/" },
          { en: "finger", zh: "手指", phonetic: "/ˈfɪŋɡər/" },
          { en: "leg", zh: "腿", phonetic: "/leɡ/" },
          { en: "foot", zh: "脚", phonetic: "/fʊt/" },
          { en: "body", zh: "身体", phonetic: "/ˈbɒdi/" },
          { en: "heart", zh: "心脏", phonetic: "/hɑːt/" },
          { en: "stomach", zh: "胃", phonetic: "/ˈstʌmək/" },
          { en: "ache", zh: "疼痛", phonetic: "/eɪk/" },
          { en: "headache", zh: "头痛", phonetic: "/ˈhedeɪk/" },
          { en: "fever", zh: "发烧", phonetic: "/ˈfiːvər/" },
          { en: "cough", zh: "咳嗽", phonetic: "/kɒf/" },
          { en: "sleep", zh: "睡觉", phonetic: "/sliːp/" },
          { en: "tired", zh: "疲倦的", phonetic: "/ˈtaɪəd/" },
          { en: "hurt", zh: "受伤；疼痛", phonetic: "/hɜːt/" },
          { en: "medicine", zh: "药", phonetic: "/ˈmedsn/" },
          { en: "hospital", zh: "医院", phonetic: "/ˈhɒspɪtl/" },
          { en: "doctor", zh: "医生", phonetic: "/ˈdɒktər/" },
          { en: "nurse", zh: "护士", phonetic: "/nɜːs/" },
          { en: "rest", zh: "休息", phonetic: "/rest/" },
          { en: "advice", zh: "建议", phonetic: "/ədˈvaɪs/" },
          { en: "missing", zh: "失踪的", phonetic: "/ˈmɪsɪŋ/" },
          { en: "worry", zh: "担心", phonetic: "/ˈwʌri/" },
          { en: "hope", zh: "希望", phonetic: "/həʊp/" },
        ]
      },
      {
        id: "7b_lab",
        name: "🤖 未来实验室",
        title: "科技改变世界",
        words: [
          { en: "future", zh: "未来", phonetic: "/ˈfjuːtʃər/" },
          { en: "technology", zh: "科技", phonetic: "/tekˈnɒlədʒi/" },
          { en: "robot", zh: "机器人", phonetic: "/ˈrəʊbɒt/" },
          { en: "machine", zh: "机器", phonetic: "/məˈʃiːn/" },
          { en: "computer", zh: "电脑", phonetic: "/kəmˈpjuːtər/" },
          { en: "website", zh: "网站", phonetic: "/ˈwebsaɪt/" },
          { en: "online", zh: "在线的", phonetic: "/ˌɒnˈlaɪn/" },
          { en: "Internet", zh: "互联网", phonetic: "/ˈɪntənet/" },
          { en: "message", zh: "消息", phonetic: "/ˈmesɪdʒ/" },
          { en: "screen", zh: "屏幕", phonetic: "/skriːn/" },
          { en: "keyboard", zh: "键盘", phonetic: "/ˈkiːbɔːd/" },
          { en: "mouse", zh: "鼠标", phonetic: "/maʊs/" },
          { en: "program", zh: "程序；节目", phonetic: "/ˈprəʊɡræm/" },
          { en: "design", zh: "设计", phonetic: "/dɪˈzaɪn/" },
          { en: "invent", zh: "发明", phonetic: "/ɪnˈvent/" },
          { en: "possible", zh: "可能的", phonetic: "/ˈpɒsəbl/" },
          { en: "impossible", zh: "不可能的", phonetic: "/ɪmˈpɒsəbl/" },
          { en: "believe", zh: "相信", phonetic: "/bɪˈliːv/" },
          { en: "perhaps", zh: "也许", phonetic: "/pəˈhæps/" },
          { en: "certainly", zh: "当然", phonetic: "/ˈsɜːtnli/" },
          { en: "actually", zh: "实际上", phonetic: "/ˈæktʃuəli/" },
          { en: "change", zh: "改变", phonetic: "/tʃeɪndʒ/" },
          { en: "develop", zh: "发展", phonetic: "/dɪˈveləp/" },
          { en: "improve", zh: "改进", phonetic: "/ɪmˈpruːv/" },
          { en: "solve", zh: "解决", phonetic: "/sɒlv/" },
          { en: "discover", zh: "发现", phonetic: "/dɪˈskʌvər/" },
          { en: "space", zh: "太空；空间", phonetic: "/speɪs/" },
          { en: "planet", zh: "行星", phonetic: "/ˈplænɪt/" },
          { en: "scientist", zh: "科学家", phonetic: "/ˈsaɪəntɪst/" },
          { en: "finally", zh: "最后", phonetic: "/ˈfaɪnəli/" },
        ]
      },
      {
        id: "7b_zoo",
        name: "🦁 野生动物园",
        title: "拜访动物王国",
        words: [
          { en: "animal", zh: "动物", phonetic: "/ˈænɪml/" },
          { en: "elephant", zh: "大象", phonetic: "/ˈelɪfənt/" },
          { en: "giraffe", zh: "长颈鹿", phonetic: "/dʒɪˈrɑːf/" },
          { en: "tiger", zh: "老虎", phonetic: "/ˈtaɪɡər/" },
          { en: "lion", zh: "狮子", phonetic: "/ˈlaɪən/" },
          { en: "monkey", zh: "猴子", phonetic: "/ˈmʌŋki/" },
          { en: "panda", zh: "熊猫", phonetic: "/ˈpændə/" },
          { en: "bear", zh: "熊", phonetic: "/beər/" },
          { en: "snake", zh: "蛇", phonetic: "/sneɪk/" },
          { en: "rabbit", zh: "兔子", phonetic: "/ˈræbɪt/" },
          { en: "horse", zh: "马", phonetic: "/hɔːs/" },
          { en: "sheep", zh: "绵羊", phonetic: "/ʃiːp/" },
          { en: "duck", zh: "鸭子", phonetic: "/dʌk/" },
          { en: "insect", zh: "昆虫", phonetic: "/ˈɪnsekt/" },
          { en: "butterfly", zh: "蝴蝶", phonetic: "/ˈbʌtəflaɪ/" },
          { en: "cute", zh: "可爱的", phonetic: "/kjuːt/" },
          { en: "tail", zh: "尾巴", phonetic: "/teɪl/" },
          { en: "bark", zh: "吠叫", phonetic: "/bɑːk/" },
          { en: "feed", zh: "喂养", phonetic: "/fiːd/" },
          { en: "owner", zh: "主人", phonetic: "/ˈəʊnər/" },
          { en: "pet", zh: "宠物", phonetic: "/pet/" },
          { en: "kill", zh: "杀死", phonetic: "/kɪl/" },
          { en: "missing", zh: "失踪的", phonetic: "/ˈmɪsɪŋ/" },
          { en: "surprise", zh: "惊喜；惊讶", phonetic: "/səˈpraɪz/" },
          { en: "afraid", zh: "害怕的", phonetic: "/əˈfreɪd/" },
          { en: "ugly", zh: "丑陋的", phonetic: "/ˈʌɡli/" },
          { en: "beautiful", zh: "美丽的", phonetic: "/ˈbjuːtɪfl/" },
          { en: "rich", zh: "富有的", phonetic: "/rɪtʃ/" },
          { en: "poor", zh: "贫穷的", phonetic: "/pɔːr/" },
          { en: "once", zh: "曾经", phonetic: "/wʌns/" },
        ]
      },
      {
        id: "7b_market",
        name: "💰 金币市场",
        title: "学会精明消费",
        words: [
          { en: "shopping", zh: "购物", phonetic: "/ˈʃɒpɪŋ/" },
          { en: "supermarket", zh: "超市", phonetic: "/ˈsuːpəmɑːkɪt/" },
          { en: "price", zh: "价格", phonetic: "/praɪs/" },
          { en: "expensive", zh: "昂贵的", phonetic: "/ɪkˈspensɪv/" },
          { en: "cheap", zh: "便宜的", phonetic: "/tʃiːp/" },
          { en: "pay", zh: "付款", phonetic: "/peɪ/" },
          { en: "cost", zh: "花费", phonetic: "/kɒst/" },
          { en: "dollar", zh: "美元", phonetic: "/ˈdɒlər/" },
          { en: "pound", zh: "英镑", phonetic: "/paʊnd/" },
          { en: "change", zh: "零钱；改变", phonetic: "/tʃeɪndʒ/" },
          { en: "receipt", zh: "收据", phonetic: "/rɪˈsiːt/" },
          { en: "customer", zh: "顾客", phonetic: "/ˈkʌstəmər/" },
          { en: "size", zh: "尺寸", phonetic: "/saɪz/" },
          { en: "colour", zh: "颜色", phonetic: "/ˈkʌlər/" },
          { en: "fashion", zh: "时尚", phonetic: "/ˈfæʃn/" },
          { en: "style", zh: "风格", phonetic: "/staɪl/" },
          { en: "comfortable", zh: "舒适的", phonetic: "/ˈkʌmftəbl/" },
          { en: "sweater", zh: "毛衣", phonetic: "/ˈswetər/" },
          { en: "jacket", zh: "夹克", phonetic: "/ˈdʒækɪt/" },
          { en: "scarf", zh: "围巾", phonetic: "/skɑːf/" },
          { en: "glove", zh: "手套", phonetic: "/ɡlʌv/" },
          { en: "sock", zh: "短袜", phonetic: "/sɒk/" },
          { en: "shoe", zh: "鞋子", phonetic: "/ʃuː/" },
          { en: "choose", zh: "选择", phonetic: "/tʃuːz/" },
          { en: "compare", zh: "比较", phonetic: "/kəmˈpeər/" },
          { en: "afford", zh: "负担得起", phonetic: "/əˈfɔːd/" },
          { en: "enough", zh: "足够的", phonetic: "/ɪˈnʌf/" },
          { en: "waste", zh: "浪费", phonetic: "/weɪst/" },
          { en: "save", zh: "节省；拯救", phonetic: "/seɪv/" },
          { en: "notice", zh: "注意到", phonetic: "/ˈnəʊtɪs/" },
        ]
      },
      {
        id: "7b_tower",
        name: "🌪️ 气象塔",
        title: "掌控风云变幻",
        words: [
          { en: "weather", zh: "天气", phonetic: "/ˈweðər/" },
          { en: "spring", zh: "春天", phonetic: "/sprɪŋ/" },
          { en: "summer", zh: "夏天", phonetic: "/ˈsʌmər/" },
          { en: "autumn", zh: "秋天", phonetic: "/ˈɔːtəm/" },
          { en: "winter", zh: "冬天", phonetic: "/ˈwɪntər/" },
          { en: "warm", zh: "温暖的", phonetic: "/wɔːm/" },
          { en: "cool", zh: "凉爽的", phonetic: "/kuːl/" },
          { en: "cold", zh: "冷的", phonetic: "/kəʊld/" },
          { en: "hot", zh: "热的", phonetic: "/hɒt/" },
          { en: "dry", zh: "干燥的", phonetic: "/draɪ/" },
          { en: "wet", zh: "潮湿的", phonetic: "/wet/" },
          { en: "rainy", zh: "下雨的", phonetic: "/ˈreɪni/" },
          { en: "snowy", zh: "下雪的", phonetic: "/ˈsnəʊi/" },
          { en: "windy", zh: "有风的", phonetic: "/ˈwɪndi/" },
          { en: "cloudy", zh: "多云的", phonetic: "/ˈklaʊdi/" },
          { en: "sunny", zh: "晴朗的", phonetic: "/ˈsʌni/" },
          { en: "foggy", zh: "有雾的", phonetic: "/ˈfɒɡi/" },
          { en: "blow", zh: "吹", phonetic: "/bləʊ/" },
          { en: "shine", zh: "照耀", phonetic: "/ʃaɪn/" },
          { en: "storm", zh: "暴风雨", phonetic: "/stɔːm/" },
          { en: "thunder", zh: "雷", phonetic: "/ˈθʌndər/" },
          { en: "lightning", zh: "闪电", phonetic: "/ˈlaɪtnɪŋ/" },
          { en: "umbrella", zh: "雨伞", phonetic: "/ʌmˈbrelə/" },
          { en: "temperature", zh: "温度", phonetic: "/ˈtemprətʃər/" },
          { en: "degree", zh: "度；学位", phonetic: "/dɪˈɡriː/" },
          { en: "above", zh: "在……上方", phonetic: "/əˈbʌv/" },
          { en: "below", zh: "在……下方", phonetic: "/bɪˈləʊ/" },
          { en: "forecast", zh: "预报", phonetic: "/ˈfɔːkɑːst/" },
          { en: "report", zh: "报告", phonetic: "/rɪˈpɔːt/" },
          { en: "depend", zh: "取决于", phonetic: "/dɪˈpend/" },
        ]
      },
      {
        id: "7b_castle",
        name: "📚 故事城堡",
        title: "书写你的传奇",
        words: [
          { en: "story", zh: "故事", phonetic: "/ˈstɔːri/" },
          { en: "poem", zh: "诗歌", phonetic: "/ˈpəʊɪm/" },
          { en: "writer", zh: "作家", phonetic: "/ˈraɪtər/" },
          { en: "novel", zh: "小说", phonetic: "/ˈnɒvl/" },
          { en: "character", zh: "角色；性格", phonetic: "/ˈkærəktər/" },
          { en: "beginning", zh: "开始", phonetic: "/bɪˈɡɪnɪŋ/" },
          { en: "middle", zh: "中间", phonetic: "/ˈmɪdl/" },
          { en: "ending", zh: "结尾", phonetic: "/ˈendɪŋ/" },
          { en: "hero", zh: "英雄", phonetic: "/ˈhɪərəʊ/" },
          { en: "princess", zh: "公主", phonetic: "/ˌprɪnˈses/" },
          { en: "king", zh: "国王", phonetic: "/kɪŋ/" },
          { en: "queen", zh: "女王", phonetic: "/kwiːn/" },
          { en: "magic", zh: "魔法", phonetic: "/ˈmædʒɪk/" },
          { en: "castle", zh: "城堡", phonetic: "/ˈkɑːsl/" },
          { en: "happen", zh: "发生", phonetic: "/ˈhæpən/" },
          { en: "suddenly", zh: "突然", phonetic: "/ˈsʌdnli/" },
          { en: "imagine", zh: "想象", phonetic: "/ɪˈmædʒɪn/" },
          { en: "describe", zh: "描述", phonetic: "/dɪˈskraɪb/" },
          { en: "adventure", zh: "冒险", phonetic: "/ədˈventʃər/" },
          { en: "terrible", zh: "糟糕的", phonetic: "/ˈterəbl/" },
          { en: "perfect", zh: "完美的", phonetic: "/ˈpɜːfɪkt/" },
          { en: "upon", zh: "在……上", phonetic: "/əˈpɒn/" },
          { en: "activity", zh: "活动", phonetic: "/ækˈtɪvəti/" },
          { en: "outdoor", zh: "户外的", phonetic: "/ˈaʊtdɔːr/" },
          { en: "indoor", zh: "室内的", phonetic: "/ˈɪndɔːr/" },
          { en: "imagine", zh: "想象", phonetic: "/ɪˈmædʒɪn/" },
          { en: "season", zh: "季节", phonetic: "/ˈsiːzn/" },
          { en: "physics", zh: "物理", phonetic: "/ˈfɪzɪks/" },
          { en: "chemistry", zh: "化学", phonetic: "/ˈkemɪstri/" },
          { en: "biology", zh: "生物", phonetic: "/baɪˈɒlədʒi/" },
        ]
      },
      {
        id: "7b_emerald",
        name: "🌍 翡翠森林",
        title: "守护我们的家园",
        words: [
          { en: "environment", zh: "环境", phonetic: "/ɪnˈvaɪrənmənt/" },
          { en: "pollute", zh: "污染", phonetic: "/pəˈluːt/" },
          { en: "rubbish", zh: "垃圾", phonetic: "/ˈrʌbɪʃ/" },
          { en: "plastic", zh: "塑料", phonetic: "/ˈplæstɪk/" },
          { en: "recycle", zh: "回收", phonetic: "/ˌriːˈsaɪkl/" },
          { en: "reduce", zh: "减少", phonetic: "/rɪˈdjuːs/" },
          { en: "reuse", zh: "重复使用", phonetic: "/ˌriːˈjuːz/" },
          { en: "waste", zh: "浪费；废物", phonetic: "/weɪst/" },
          { en: "electricity", zh: "电", phonetic: "/ɪˌlekˈtrɪsəti/" },
          { en: "factory", zh: "工厂", phonetic: "/ˈfæktri/" },
          { en: "smoke", zh: "烟", phonetic: "/sməʊk/" },
          { en: "dirty", zh: "脏的", phonetic: "/ˈdɜːti/" },
          { en: "clean", zh: "干净的；清洁", phonetic: "/kliːn/" },
          { en: "breathe", zh: "呼吸", phonetic: "/briːð/" },
          { en: "ocean", zh: "海洋", phonetic: "/ˈəʊʃn/" },
          { en: "river", zh: "河流", phonetic: "/ˈrɪvər/" },
          { en: "lake", zh: "湖泊", phonetic: "/leɪk/" },
          { en: "destroy", zh: "破坏", phonetic: "/dɪˈstrɔɪ/" },
          { en: "cause", zh: "导致", phonetic: "/kɔːz/" },
          { en: "instead", zh: "代替", phonetic: "/ɪnˈsted/" },
          { en: "government", zh: "政府", phonetic: "/ˈɡʌvənmənt/" },
          { en: "law", zh: "法律", phonetic: "/lɔː/" },
          { en: "action", zh: "行动", phonetic: "/ˈækʃn/" },
          { en: "forest", zh: "森林", phonetic: "/ˈfɒrɪst/" },
          { en: "plant", zh: "植物；种植", phonetic: "/plɑːnt/" },
          { en: "animal", zh: "动物", phonetic: "/ˈænɪml/" },
          { en: "natural", zh: "自然的", phonetic: "/ˈnætʃrəl/" },
          { en: "energy", zh: "能量", phonetic: "/ˈenədʒi/" },
          { en: "develop", zh: "发展", phonetic: "/dɪˈveləp/" },
          { en: "future", zh: "未来", phonetic: "/ˈfjuːtʃər/" },
        ]
      },
    ]
  },
  exam: {
    cloze: [
      {
        id: "cloze_1",
        name: "🎯 完形特训·上",
        title: "近义词辨析",
        words: [
          { en: "accept", zh: "接受", phonetic: "/əkˈsept/" },
          { en: "receive", zh: "收到", phonetic: "/rɪˈsiːv/" },
          { en: "except", zh: "除了", phonetic: "/ɪkˈsept/" },
          { en: "expect", zh: "期望", phonetic: "/ɪkˈspekt/" },
          { en: "affect", zh: "影响", phonetic: "/əˈfekt/" },
          { en: "effect", zh: "效果", phonetic: "/ɪˈfekt/" },
          { en: "effort", zh: "努力", phonetic: "/ˈefət/" },
          { en: "offer", zh: "提供", phonetic: "/ˈɒfər/" },
          { en: "allow", zh: "允许", phonetic: "/əˈlaʊ/" },
          { en: "agree", zh: "同意", phonetic: "/əˈɡriː/" },
          { en: "argue", zh: "争论", phonetic: "/ˈɑːɡjuː/" },
          { en: "achieve", zh: "达到；实现", phonetic: "/əˈtʃiːv/" },
          { en: "avoid", zh: "避免", phonetic: "/əˈvɔɪd/" },
          { en: "attend", zh: "参加", phonetic: "/əˈtend/" },
          { en: "attract", zh: "吸引", phonetic: "/əˈtrækt/" },
          { en: "doubt", zh: "怀疑", phonetic: "/daʊt/" },
          { en: "suppose", zh: "认为；假设", phonetic: "/səˈpəʊz/" },
          { en: "consider", zh: "考虑", phonetic: "/kənˈsɪdər/" },
          { en: "suggest", zh: "建议", phonetic: "/səˈdʒest/" },
          { en: "advise", zh: "劝告", phonetic: "/ədˈvaɪz/" },
          { en: "promise", zh: "承诺", phonetic: "/ˈprɒmɪs/" },
          { en: "refuse", zh: "拒绝", phonetic: "/rɪˈfjuːz/" },
          { en: "regret", zh: "后悔", phonetic: "/rɪˈɡret/" },
          { en: "decide", zh: "决定", phonetic: "/dɪˈsaɪd/" },
          { en: "depend", zh: "依靠", phonetic: "/dɪˈpend/" },
          { en: "realize", zh: "意识到", phonetic: "/ˈrɪəlaɪz/" },
          { en: "recognize", zh: "认出", phonetic: "/ˈrekəɡnaɪz/" },
          { en: "require", zh: "需要", phonetic: "/rɪˈkwaɪər/" },
          { en: "provide", zh: "提供", phonetic: "/prəˈvaɪd/" },
          { en: "prevent", zh: "阻止", phonetic: "/prɪˈvent/" },
        ]
      },
      {
        id: "cloze_2",
        name: "🎯 完形特训·下",
        title: "连词与逻辑衔接",
        words: [
          { en: "however", zh: "然而", phonetic: "/haʊˈevər/" },
          { en: "therefore", zh: "因此", phonetic: "/ˈðeəfɔːr/" },
          { en: "although", zh: "尽管", phonetic: "/ɔːlˈðəʊ/" },
          { en: "because", zh: "因为", phonetic: "/bɪˈkɒz/" },
          { en: "unless", zh: "除非", phonetic: "/ʌnˈles/" },
          { en: "whether", zh: "是否", phonetic: "/ˈweðər/" },
          { en: "while", zh: "当……时；然而", phonetic: "/waɪl/" },
          { en: "since", zh: "自从；因为", phonetic: "/sɪns/" },
          { en: "until", zh: "直到", phonetic: "/ʌnˈtɪl/" },
          { en: "before", zh: "在……之前", phonetic: "/bɪˈfɔːr/" },
          { en: "after", zh: "在……之后", phonetic: "/ˈɑːftər/" },
          { en: "besides", zh: "此外", phonetic: "/bɪˈsaɪdz/" },
          { en: "instead", zh: "代替", phonetic: "/ɪnˈsted/" },
          { en: "already", zh: "已经", phonetic: "/ɔːlˈredi/" },
          { en: "almost", zh: "几乎", phonetic: "/ˈɔːlməʊst/" },
          { en: "nearly", zh: "将近", phonetic: "/ˈnɪəli/" },
          { en: "especially", zh: "尤其", phonetic: "/ɪˈspeʃəli/" },
          { en: "exactly", zh: "确切地", phonetic: "/ɪɡˈzæktli/" },
          { en: "probably", zh: "很可能", phonetic: "/ˈprɒbəbli/" },
          { en: "certainly", zh: "当然", phonetic: "/ˈsɜːtnli/" },
          { en: "hardly", zh: "几乎不", phonetic: "/ˈhɑːdli/" },
          { en: "seldom", zh: "很少", phonetic: "/ˈseldəm/" },
          { en: "never", zh: "从不", phonetic: "/ˈnevər/" },
          { en: "usually", zh: "通常", phonetic: "/ˈjuːʒuəli/" },
          { en: "together", zh: "一起", phonetic: "/təˈɡeðər/" },
          { en: "without", zh: "没有", phonetic: "/wɪˈðaʊt/" },
          { en: "during", zh: "在……期间", phonetic: "/ˈdjʊərɪŋ/" },
          { en: "through", zh: "穿过", phonetic: "/θruː/" },
          { en: "though", zh: "虽然", phonetic: "/ðəʊ/" },
          { en: "perhaps", zh: "也许", phonetic: "/pəˈhæps/" },
        ]
      }
    ],
    reading: [
      {
        id: "reading_1",
        name: "📖 阅读特训·上",
        title: "学术说明文词汇",
        words: [
          { en: "research", zh: "研究", phonetic: "/rɪˈsɜːtʃ/" },
          { en: "experiment", zh: "实验", phonetic: "/ɪkˈsperɪmənt/" },
          { en: "result", zh: "结果", phonetic: "/rɪˈzʌlt/" },
          { en: "reason", zh: "原因", phonetic: "/ˈriːzn/" },
          { en: "example", zh: "例子", phonetic: "/ɪɡˈzɑːmpl/" },
          { en: "method", zh: "方法", phonetic: "/ˈmeθəd/" },
          { en: "process", zh: "过程", phonetic: "/ˈprəʊses/" },
          { en: "purpose", zh: "目的", phonetic: "/ˈpɜːpəs/" },
          { en: "opinion", zh: "观点", phonetic: "/əˈpɪnjən/" },
          { en: "evidence", zh: "证据", phonetic: "/ˈevɪdəns/" },
          { en: "according", zh: "根据", phonetic: "/əˈkɔːdɪŋ/" },
          { en: "including", zh: "包括", phonetic: "/ɪnˈkluːdɪŋ/" },
          { en: "generally", zh: "通常", phonetic: "/ˈdʒenrəli/" },
          { en: "explain", zh: "解释", phonetic: "/ɪkˈspleɪn/" },
          { en: "describe", zh: "描述", phonetic: "/dɪˈskraɪb/" },
          { en: "mention", zh: "提到", phonetic: "/ˈmenʃn/" },
          { en: "express", zh: "表达", phonetic: "/ɪkˈspres/" },
          { en: "discuss", zh: "讨论", phonetic: "/dɪˈskʌs/" },
          { en: "introduce", zh: "介绍", phonetic: "/ˌɪntrəˈdjuːs/" },
          { en: "increase", zh: "增加", phonetic: "/ɪnˈkriːs/" },
          { en: "decrease", zh: "减少", phonetic: "/dɪˈkriːs/" },
          { en: "continue", zh: "继续", phonetic: "/kənˈtɪnjuː/" },
          { en: "produce", zh: "生产；产生", phonetic: "/prəˈdjuːs/" },
          { en: "control", zh: "控制", phonetic: "/kənˈtrəʊl/" },
          { en: "connect", zh: "连接", phonetic: "/kəˈnekt/" },
          { en: "contain", zh: "包含", phonetic: "/kənˈteɪn/" },
          { en: "compare", zh: "比较", phonetic: "/kəmˈpeər/" },
          { en: "support", zh: "支持", phonetic: "/səˈpɔːt/" },
          { en: "require", zh: "需要", phonetic: "/rɪˈkwaɪər/" },
          { en: "include", zh: "包含", phonetic: "/ɪnˈkluːd/" },
        ]
      },
      {
        id: "reading_2",
        name: "📖 阅读特训·下",
        title: "熟词生义与推断",
        words: [
          { en: "book", zh: "书；预订", phonetic: "/bʊk/" },
          { en: "bank", zh: "银行；河岸", phonetic: "/bæŋk/" },
          { en: "bear", zh: "熊；忍受", phonetic: "/beər/" },
          { en: "case", zh: "情况；箱子", phonetic: "/keɪs/" },
          { en: "charge", zh: "收费；充电", phonetic: "/tʃɑːdʒ/" },
          { en: "clear", zh: "清楚的；清理", phonetic: "/klɪər/" },
          { en: "cover", zh: "覆盖；封面", phonetic: "/ˈkʌvər/" },
          { en: "cross", zh: "穿过；生气的", phonetic: "/krɒs/" },
          { en: "date", zh: "日期；约会", phonetic: "/deɪt/" },
          { en: "direct", zh: "直接的；导演", phonetic: "/dɪˈrekt/" },
          { en: "fair", zh: "公平的；集市", phonetic: "/feər/" },
          { en: "figure", zh: "数字；人物", phonetic: "/ˈfɪɡər/" },
          { en: "fine", zh: "好的；罚款", phonetic: "/faɪn/" },
          { en: "flat", zh: "平的；公寓", phonetic: "/flæt/" },
          { en: "form", zh: "形式；形成", phonetic: "/fɔːm/" },
          { en: "head", zh: "头；前往", phonetic: "/hed/" },
          { en: "interest", zh: "兴趣；利息", phonetic: "/ˈɪntrəst/" },
          { en: "light", zh: "光；轻的", phonetic: "/laɪt/" },
          { en: "match", zh: "比赛；匹配", phonetic: "/mætʃ/" },
          { en: "mean", zh: "意思是；吝啬的", phonetic: "/miːn/" },
          { en: "mind", zh: "介意；头脑", phonetic: "/maɪnd/" },
          { en: "note", zh: "笔记；注意到", phonetic: "/nəʊt/" },
          { en: "order", zh: "顺序；命令", phonetic: "/ˈɔːdər/" },
          { en: "point", zh: "点；指出", phonetic: "/pɔɪnt/" },
          { en: "raise", zh: "举起；筹集", phonetic: "/reɪz/" },
          { en: "second", zh: "第二；秒", phonetic: "/ˈsekənd/" },
          { en: "sense", zh: "感觉；意义", phonetic: "/sens/" },
          { en: "subject", zh: "主题；科目", phonetic: "/ˈsʌbdʒɪkt/" },
          { en: "change", zh: "改变；零钱", phonetic: "/tʃeɪndʒ/" },
          { en: "present", zh: "礼物；呈现", phonetic: "/ˈpreznt/" },
        ]
      }
    ],
    writing: [
      {
        id: "writing_1",
        name: "✍️ 写作秘技",
        title: "高分过渡词与替换",
        words: [
          { en: "firstly", zh: "首先", phonetic: "/ˈfɜːstli/" },
          { en: "secondly", zh: "其次", phonetic: "/ˈsekəndli/" },
          { en: "finally", zh: "最后", phonetic: "/ˈfaɪnəli/" },
          { en: "moreover", zh: "此外", phonetic: "/mɔːrˈəʊvər/" },
          { en: "furthermore", zh: "而且", phonetic: "/ˌfɜːðəˈmɔːr/" },
          { en: "however", zh: "然而", phonetic: "/haʊˈevər/" },
          { en: "therefore", zh: "因此", phonetic: "/ˈðeəfɔːr/" },
          { en: "meanwhile", zh: "同时", phonetic: "/ˈmiːnwaɪl/" },
          { en: "otherwise", zh: "否则", phonetic: "/ˈʌðəwaɪz/" },
          { en: "actually", zh: "实际上", phonetic: "/ˈæktʃuəli/" },
          { en: "obviously", zh: "显然", phonetic: "/ˈɒbviəsli/" },
          { en: "fortunately", zh: "幸运地", phonetic: "/ˈfɔːtʃənətli/" },
          { en: "unfortunately", zh: "不幸地", phonetic: "/ʌnˈfɔːtʃənətli/" },
          { en: "gradually", zh: "逐渐地", phonetic: "/ˈɡrædʒuəli/" },
          { en: "excellent", zh: "优秀的", phonetic: "/ˈeksələnt/" },
          { en: "wonderful", zh: "精彩的", phonetic: "/ˈwʌndəfl/" },
          { en: "fantastic", zh: "极好的", phonetic: "/fænˈtæstɪk/" },
          { en: "terrible", zh: "糟糕的", phonetic: "/ˈterəbl/" },
          { en: "various", zh: "各种各样的", phonetic: "/ˈveəriəs/" },
          { en: "necessary", zh: "必要的", phonetic: "/ˈnesəsəri/" },
          { en: "possible", zh: "可能的", phonetic: "/ˈpɒsəbl/" },
          { en: "convenient", zh: "方便的", phonetic: "/kənˈviːniənt/" },
          { en: "experience", zh: "经历；经验", phonetic: "/ɪkˈspɪəriəns/" },
          { en: "opportunity", zh: "机会", phonetic: "/ˌɒpəˈtjuːnəti/" },
          { en: "challenge", zh: "挑战", phonetic: "/ˈtʃælɪndʒ/" },
          { en: "improve", zh: "改进", phonetic: "/ɪmˈpruːv/" },
          { en: "develop", zh: "发展", phonetic: "/dɪˈveləp/" },
          { en: "succeed", zh: "成功", phonetic: "/səkˈsiːd/" },
          { en: "influence", zh: "影响", phonetic: "/ˈɪnfluəns/" },
          { en: "attitude", zh: "态度", phonetic: "/ˈætɪtjuːd/" },
          { en: "benefit", zh: "好处；受益", phonetic: "/ˈbenɪfɪt/" },
          { en: "relationship", zh: "关系", phonetic: "/rɪˈleɪʃnʃɪp/" },
          { en: "communication", zh: "交流", phonetic: "/kəˌmjuːnɪˈkeɪʃn/" },
          { en: "independent", zh: "独立的", phonetic: "/ˌɪndɪˈpendənt/" },
          { en: "responsible", zh: "负责的", phonetic: "/rɪˈspɒnsəbl/" },
          { en: "encourage", zh: "鼓励", phonetic: "/ɪnˈkʌrɪdʒ/" },
          { en: "knowledge", zh: "知识", phonetic: "/ˈnɒlɪdʒ/" },
          { en: "environment", zh: "环境", phonetic: "/ɪnˈvaɪrənmənt/" },
          { en: "comfortable", zh: "舒适的", phonetic: "/ˈkʌmftəbl/" },
          { en: "important", zh: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
        ]
      }
    ],
    phrasal: [
      {
        id: "phrasal_1",
        name: "🔗 短语特训·上",
        title: "look/put/take 家族",
        words: [
          { en: "look after", zh: "照顾", phonetic: "" },
          { en: "look for", zh: "寻找", phonetic: "" },
          { en: "look forward to", zh: "期待", phonetic: "" },
          { en: "look up", zh: "查阅", phonetic: "" },
          { en: "look out", zh: "小心", phonetic: "" },
          { en: "put on", zh: "穿上", phonetic: "" },
          { en: "put off", zh: "推迟", phonetic: "" },
          { en: "put up", zh: "张贴；搭建", phonetic: "" },
          { en: "put away", zh: "收起来", phonetic: "" },
          { en: "put out", zh: "熄灭", phonetic: "" },
          { en: "take off", zh: "起飞；脱下", phonetic: "" },
          { en: "take care of", zh: "照顾", phonetic: "" },
          { en: "take part in", zh: "参加", phonetic: "" },
          { en: "take place", zh: "发生", phonetic: "" },
          { en: "take up", zh: "开始从事", phonetic: "" },
          { en: "give up", zh: "放弃", phonetic: "" },
          { en: "give away", zh: "赠送", phonetic: "" },
          { en: "give out", zh: "分发", phonetic: "" },
          { en: "give back", zh: "归还", phonetic: "" },
          { en: "come up with", zh: "想出", phonetic: "" },
          { en: "come true", zh: "实现", phonetic: "" },
          { en: "come across", zh: "偶遇", phonetic: "" },
          { en: "come back", zh: "回来", phonetic: "" },
          { en: "come from", zh: "来自", phonetic: "" },
          { en: "go on", zh: "继续", phonetic: "" },
        ]
      },
      {
        id: "phrasal_2",
        name: "🔗 短语特训·下",
        title: "get/turn/核心动词",
        words: [
          { en: "get up", zh: "起床", phonetic: "" },
          { en: "get on", zh: "上车；进展", phonetic: "" },
          { en: "get off", zh: "下车", phonetic: "" },
          { en: "get along with", zh: "与……相处", phonetic: "" },
          { en: "get ready for", zh: "为……准备", phonetic: "" },
          { en: "get used to", zh: "习惯于", phonetic: "" },
          { en: "turn on", zh: "打开", phonetic: "" },
          { en: "turn off", zh: "关掉", phonetic: "" },
          { en: "turn up", zh: "调大；出现", phonetic: "" },
          { en: "turn down", zh: "调小；拒绝", phonetic: "" },
          { en: "turn into", zh: "变成", phonetic: "" },
          { en: "make sure", zh: "确保", phonetic: "" },
          { en: "make up", zh: "编造；弥补", phonetic: "" },
          { en: "make friends", zh: "交朋友", phonetic: "" },
          { en: "make a decision", zh: "做决定", phonetic: "" },
          { en: "set up", zh: "建立", phonetic: "" },
          { en: "set off", zh: "出发", phonetic: "" },
          { en: "pick up", zh: "捡起；接人", phonetic: "" },
          { en: "wake up", zh: "醒来", phonetic: "" },
          { en: "grow up", zh: "长大", phonetic: "" },
          { en: "find out", zh: "查明", phonetic: "" },
          { en: "work out", zh: "解决；锻炼", phonetic: "" },
          { en: "carry on", zh: "继续", phonetic: "" },
          { en: "give in", zh: "屈服", phonetic: "" },
          { en: "fall asleep", zh: "入睡", phonetic: "" },
        ]
      }
    ]
  },
  tricky: {
    spelling: [
      {
        id: "spelling_1",
        name: "⚠️ 易错迷宫",
        title: "拼写陷阱词",
        words: [
          { en: "beautiful", zh: "美丽的", phonetic: "/ˈbjuːtɪfl/" },
          { en: "different", zh: "不同的", phonetic: "/ˈdɪfrənt/" },
          { en: "difficult", zh: "困难的", phonetic: "/ˈdɪfɪkəlt/" },
          { en: "important", zh: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
          { en: "interesting", zh: "有趣的", phonetic: "/ˈɪntrəstɪŋ/" },
          { en: "Wednesday", zh: "星期三", phonetic: "/ˈwenzdeɪ/" },
          { en: "February", zh: "二月", phonetic: "/ˈfebruəri/" },
          { en: "autumn", zh: "秋天", phonetic: "/ˈɔːtəm/" },
          { en: "island", zh: "岛屿", phonetic: "/ˈaɪlənd/" },
          { en: "knowledge", zh: "知识", phonetic: "/ˈnɒlɪdʒ/" },
          { en: "neighbour", zh: "邻居", phonetic: "/ˈneɪbər/" },
          { en: "restaurant", zh: "餐厅", phonetic: "/ˈrestrɒnt/" },
          { en: "sandwich", zh: "三明治", phonetic: "/ˈsænwɪdʒ/" },
          { en: "language", zh: "语言", phonetic: "/ˈlæŋɡwɪdʒ/" },
          { en: "foreign", zh: "外国的", phonetic: "/ˈfɒrən/" },
          { en: "government", zh: "政府", phonetic: "/ˈɡʌvənmənt/" },
          { en: "environment", zh: "环境", phonetic: "/ɪnˈvaɪrənmənt/" },
          { en: "temperature", zh: "温度", phonetic: "/ˈtemprətʃər/" },
          { en: "comfortable", zh: "舒适的", phonetic: "/ˈkʌmftəbl/" },
          { en: "necessary", zh: "必要的", phonetic: "/ˈnesəsəri/" },
          { en: "address", zh: "地址", phonetic: "/əˈdres/" },
          { en: "arrive", zh: "到达", phonetic: "/əˈraɪv/" },
          { en: "believe", zh: "相信", phonetic: "/bɪˈliːv/" },
          { en: "receive", zh: "收到", phonetic: "/rɪˈsiːv/" },
          { en: "business", zh: "生意", phonetic: "/ˈbɪznəs/" },
          { en: "surprise", zh: "惊喜", phonetic: "/səˈpraɪz/" },
          { en: "practise", zh: "练习（动词）", phonetic: "/ˈpræktɪs/" },
          { en: "success", zh: "成功", phonetic: "/səkˈses/" },
          { en: "exercise", zh: "锻炼", phonetic: "/ˈeksəsaɪz/" },
          { en: "grammar", zh: "语法", phonetic: "/ˈɡræmər/" },
        ]
      }
    ],
    similar: [
      {
        id: "similar_1",
        name: "🔍 幻影双生",
        title: "形近音近词对决",
        words: [
          { en: "quite", zh: "相当", phonetic: "/kwaɪt/" },
          { en: "quiet", zh: "安静的", phonetic: "/ˈkwaɪət/" },
          { en: "affect", zh: "影响", phonetic: "/əˈfekt/" },
          { en: "effect", zh: "效果", phonetic: "/ɪˈfekt/" },
          { en: "accept", zh: "接受", phonetic: "/əkˈsept/" },
          { en: "except", zh: "除了", phonetic: "/ɪkˈsept/" },
          { en: "advice", zh: "建议（名词）", phonetic: "/ədˈvaɪs/" },
          { en: "advise", zh: "建议（动词）", phonetic: "/ədˈvaɪz/" },
          { en: "breath", zh: "呼吸（名词）", phonetic: "/breθ/" },
          { en: "breathe", zh: "呼吸（动词）", phonetic: "/briːð/" },
          { en: "than", zh: "比", phonetic: "/ðæn/" },
          { en: "then", zh: "然后", phonetic: "/ðen/" },
          { en: "through", zh: "穿过", phonetic: "/θruː/" },
          { en: "though", zh: "虽然", phonetic: "/ðəʊ/" },
          { en: "thought", zh: "想法", phonetic: "/θɔːt/" },
          { en: "lose", zh: "失去", phonetic: "/luːz/" },
          { en: "loose", zh: "松的", phonetic: "/luːs/" },
          { en: "price", zh: "价格", phonetic: "/praɪs/" },
          { en: "prize", zh: "奖品", phonetic: "/praɪz/" },
          { en: "weather", zh: "天气", phonetic: "/ˈweðər/" },
          { en: "whether", zh: "是否", phonetic: "/ˈweðər/" },
          { en: "desert", zh: "沙漠", phonetic: "/ˈdezət/" },
          { en: "dessert", zh: "甜点", phonetic: "/dɪˈzɜːt/" },
          { en: "abroad", zh: "在国外", phonetic: "/əˈbrɔːd/" },
          { en: "aboard", zh: "在船上", phonetic: "/əˈbɔːd/" },
        ]
      }
    ]
  }
};

function getAllWords() {
  const all = [];
  for (const grade of ['grade7a', 'grade7b']) {
    for (const unit of WORD_DATA.textbook[grade]) {
      all.push(...unit.words);
    }
  }
  for (const cat of ['cloze', 'reading', 'writing', 'phrasal']) {
    for (const unit of WORD_DATA.exam[cat]) {
      all.push(...unit.words);
    }
  }
  for (const cat of ['spelling', 'similar']) {
    for (const unit of WORD_DATA.tricky[cat]) {
      all.push(...unit.words);
    }
  }
  return all;
}

function getAllUnits() {
  const units = [];
  for (const grade of ['grade7a', 'grade7b']) {
    for (const unit of WORD_DATA.textbook[grade]) {
      units.push({ ...unit, module: 'textbook', grade });
    }
  }
  for (const cat of ['cloze', 'reading', 'writing', 'phrasal']) {
    for (const unit of WORD_DATA.exam[cat]) {
      units.push({ ...unit, module: 'exam', category: cat });
    }
  }
  for (const cat of ['spelling', 'similar']) {
    for (const unit of WORD_DATA.tricky[cat]) {
      units.push({ ...unit, module: 'tricky', category: cat });
    }
  }
  return units;
}
